### ISSUE TITLE
Output parameter seems to be wrong in docs

### ISSUE THREAD

**Issue by davestewart** [rawcreative/vueify-extract-css#2]
In testing the Elixir plugin, I kept getting:

```
Error: EISDIR: illegal operation on a directory, open '/Volumes/Data/Work/Current/2015-07 - Timeslice, Kiosk 3.0/timeslice.kiosk/public/assets/vue'
```

Turns out this error regards outputting to a folder, when it should be a file.

Changing this:

```
out: 'path/to/extracted/css'
```

To this:

```
out: 'path/to/extracted.css'
```

Solved the file output.

( Though the file is still empty, as noted in #1 )

**Comment by rawcreative** [comment]
If you're using elixir you can't pass a reference to the plugin, you have to pass the plugin name as a string because elixir 'requires' the plugin name you pass. Yes in all instances/methods for using the plugin, the output param needs to be a file, not directory

**Comment by davestewart** [comment]
Hi Tim, in this case I am passing the string name, verbatim (apart from the `.css`) as per your example.

```
    elixir.config.js.browserify.plugins.push({
        name: 'vueify-extract-css',
        options: {
            out: path.normalize(__dirname + '/../public/assets/vue/bundle.css')
        }
    });

```

I have all my supporting files in a subfolder, hence the path.normalize.

The CSS file is created, it's just still empty.

**Comment by rawcreative** [comment]
Which version of vueify are you using? You noted 0.1.0 in #1 but that must be for this plugin, not for vueify itself. Actually better yet, could you just post the dependencies/dev-dependencies in your package.json?

**Comment by davestewart** [comment]
Sure:

```
{
  "private": true,
  "devDependencies": {
    "gulp": "^3.9.0",
    "gulp-util": "^3.0.7",
    "laravel-elixir": "^4.0.4",
    "laravel-elixir-vueify": "^1.0.3"
  },
  "dependencies": {
    "babel-preset-es2015": "^6.9.0",
    "babel-preset-react": "^6.5.0"
  }
}
```

FYI: #1 is vanilla Gulp. This ticket is for Elixir (I'm trying to compare build systems)

**Comment by rawcreative** [comment]
ReadMe updated
