### ISSUE TITLE
Generated CSS is empty

### ISSUE THREAD

**Issue by graphek** [rawcreative/vueify-extract-css#3]
Hi,

i really like the idea of this plugin, but i think i am missing something. The bundle.css is being generated, but it's empty. The CSS gets appended to the head for each of my Vue-Modules seperatly (like before, but it's kind of ugly, so i'd like to have just one bundled CSS File to include). 

Here's my Gulpfile.js:

```
var elixir = require('laravel-elixir');
var gutils = require('gulp-util');

require('laravel-elixir-vueify');

process.env.NODE_ENV = 'development';
elixir.config.production = false;
elixir.config.assetsPath = "";

elixir.config.js.browserify.plugins.push({
    name: 'vueify-extract-css',
    options: {
        out: 'mybundle.css'
    }
});

if(gutils.env._.indexOf('watch') > -1) {
    elixir.config.js.browserify.plugins.push({
        name: "browserify-hmr",
        options : {
          // mode: 'fs',
          // p: 9090
        }
    });
}

elixir(function(mix) {

  mix.browserify('./_app/main.js');

});

```

Do you have an idea?

best regards

**Comment by rawcreative** [comment]
Which version of Vueify are you using? 

I ask because in version 8.6.0 of Vueify, the code that handles inserting the css was changed. If you're using Vueify 8.6.0+ you'll need to use version 0.2.0 of this plugin, but if you're using 8.4.1 or below, you'll need to use version 0.1.0.

**Comment by graphek** [comment]
Hi,

thanks for your fast reply, that was the hint i needed! It's not working with the laravel-elixir-vuefiy package (at least the way i tried it), instead i plugged in vuefiy as browserify transformer by my own. 

If case anyone is interested, here is my working gulpfile:

```
var elixir = require('laravel-elixir');
var gutils = require('gulp-util');

process.env.NODE_ENV = 'development';
elixir.config.production = false;
elixir.config.assetsPath = "";

elixir.config.js.browserify.plugins.push({
    name: 'vueify-extract-css',
    options: {
        out: 'public/assets/coroom.css'
    }
});

if(gutils.env._.indexOf('watch') > -1) {
    elixir.config.js.browserify.plugins.push({
        name: "browserify-hmr",
        options : {
          // mode: 'fs',
          // p: 9090
        }
    });
}

  elixir.config.js.browserify.transformers.push({
      name: "vueify",
      options : {}
  });


elixir(function(mix) {

  mix.browserify('./_app/main.js');

});
```

best regards

**Comment by rawcreative** [comment]
It looks like the current version of laravel-elixir-vuefiy is using version 8.3.0 of vueify, so you would need to pull in version 0.1.0 of this plugin for it to work as expected.
